CREATE TABLE IF NOT EXISTS reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batch VARCHAR(100),
    client_name VARCHAR(255),
    property_type VARCHAR(100),
    address VARCHAR(255),
    location_coordinates VARCHAR(100),
    property_description TEXT,
    property_occupancy VARCHAR(100),
    property_tenure VARCHAR(100),
    property_status VARCHAR(100),
    developer VARCHAR(255),
    floors VARCHAR(100),
    bua_sqm DECIMAL(12,2),
    bua_sqft DECIMAL(12,2),
    land_plot_size_sqm DECIMAL(12,2),
    land_plot_size_sqft DECIMAL(12,2),
    purpose_of_valuation VARCHAR(255),
    date_of_valuation DATE,
    capacity_of_valuer VARCHAR(100),
    method_of_valuation VARCHAR(100),
    transaction_range VARCHAR(255),
    adopted_rate_per_sqft DECIMAL(12,2),
    market_value_rounded DECIMAL(15,2),
    subject_to_valuation VARCHAR(255),
    forced_sale_value_aed DECIMAL(15,2),
    annual_rent_aed DECIMAL(15,2),
    comparable_image VARCHAR(255),
    status VARCHAR(50),
    file_path VARCHAR(255),
    progress TINYINT DEFAULT 0,
    created_at DATETIME,
    generated_at DATETIME
);

CREATE TABLE IF NOT EXISTS report_queue (
    id INT AUTO_INCREMENT PRIMARY KEY,
    report_id INT NOT NULL,
    status ENUM('pending','processing','done','failed') DEFAULT 'pending',
    created_at DATETIME,
    updated_at DATETIME,
    FOREIGN KEY (report_id) REFERENCES reports(id)
);
